### ISSUE TITLE
Repetición de lógica

### ISSUE THREAD

**Issue by delucas** [Grace-Hopper/TPAsistenteVirtual3#4]
Este método tiene tres repeticiones de código, que son esencialmente iguales. Reutilicen código.

Adicionalmente, utilizan `while` para una condición. Eso no es correcto.

https://github.com/Grace-Hopper/TPAsistenteVirtual3/blob/2f4d19227f2dad8dd7281bbdd628df71e9a9052c/src/operacion/FechaActual.java#L18

**Comment by NicoDelRio** [comment]
Se corrigió usando un solo regex y eliminando el while.
